### ISSUE TITLE
ODrive Telemetry

### ISSUE THREAD

**Issue by tame0001** [boilerrobotics/rover-code#88]
We need to add a function periodically read Odrive value. Let's start with [voltage ](https://docs.odriverobotics.com/v/0.5.6/fibre_types/com_odriverobotics_ODrive.html#ODrive.vbus_voltage), [current](https://docs.odriverobotics.com/v/0.5.6/fibre_types/com_odriverobotics_ODrive.html#ODrive.vbus_voltage). These two parameters are Odrive basic. So, there will be 6 values. 
Next, it would be nice to experiment with other parameters. I don't have done this before, so I can only point to potential parameters. [mechanical power](https://docs.odriverobotics.com/v/0.5.6/fibre_types/com_odriverobotics_ODrive.html#ODrive.Controller.mechanical_power), [electrical power](https://docs.odriverobotics.com/v/0.5.6/fibre_types/com_odriverobotics_ODrive.html#ODrive.Controller.electrical_power), [estimated velocity](https://docs.odriverobotics.com/v/0.5.6/fibre_types/com_odriverobotics_ODrive.html#ODrive.Encoder.vel_estimate). 

We will need to create a custom message for these parameters. The structure of the message is debatable. As well as the topic name. I am open to hearing what you think. 

The challenge is we probably cannot write a dedicated package for this task since `drive` occupies the Odrive abstract. We need to add this function into `drive` package (still okay to write another file then import to `drive`'s main file. We will need to create a periodical task but how to do that in the most effective way is still a question. Using `time.sleep()` is probably not a good idea as it will block the process. Let's think about it. 

The end goal is to send this information as a topic to the base station. Then I will run MQTT bridge on the base station and pass this data to GUI.

**Comment by ky28059** [comment]
I think we can probably use the ROS built-in `Timer` class? It's able to run a callback on a loop which is what we want here, and it doesn't block the process when doing so.

**Comment by tame0001** [comment]
More requirements:

- Send error messages. Check `check_error` function on this file: https://github.com/boilerrobotics/rover-code/blob/odrive-telemetry/components/odrive/utils.py

- Test with subscriber -> https://github.com/boilerrobotics/base-station/issues/3. It is not required to run both code in two separated machines. You can run both in the same machine on the different terminals. 

- [optional] It will be more convenient if we can run and test the code with only 1 ODrive at a time. Function `find_odrives` in this file https://github.com/boilerrobotics/rover-code/blob/odrive-telemetry/components/odrive/utils.py experiment on that concept. If you think it work, try to add in to the package
